---
abstract: 'define subs that act like `return`'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.012, CPAN::Meta::Converter version 2.120921'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: returning
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  returning:
    file: lib/returning.pm
    version: 0.002
requires:
  Scalar::Util: 1.11
  Scope::Upper: 0.16
  Sub::Install: 0.900
  Sub::Name: 0.03
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/returning/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=returning
  homepage: https://metacpan.org/release/returning
  license: http://dev.perl.org/licenses/
  repository: https://github.com/tobyink/p5-returning
version: 0.002
